### PR TITLE
Support JDK 11

### PR DESCRIPTION
**Pull request by michaelcarr-bilue**

### CODE REVIEW

**Review by kartikarora — APPROVED** [review]

**Review by KatieBarnett — APPROVED** [review]

**Comment by damiandara** [comment]
Hey guys, I don't know how but I somehow got notified about your PR request haha Somehow I still have access to this repo 😁

**Comment by nicolas98320** [comment]
Same 😅

**Review by damiandara — APPROVED** [review]

**Comment by damiandara** [comment]
> Same 😅
> […](#)

😁

**Comment by rjayne** [comment]
Me too!

**Comment by kartikarora** [comment]
@damiandara @nicolas98320 @rjayne 
Hi all. It is a public repo and you are probably subcribed to all public repos under Bilue github org, hence the notification. :)

**Comment by damiandara** [comment]
That makes sense. Thanks for confirming @kartikarora 🙌

**Pull request merged**
